### ISSUE TITLE
Rename repo to softe.club

### ISSUE THREAD

**Issue by adapap** [StevensSEC/softe.club#194]
Was just wondering if there was any reason to keep sec.club as the name.

**Comment by dyc3** [comment]
I was avoiding having to fix everyone's local git copy because the remote url would change, but yeah this needs to happen.

**Comment by carpenterd777** [comment]
Its been done. Sorry to everyone who's local copy is messed up now!

**Comment by dyc3** [comment]
The link on the website footer also needs to be fixed
