### ISSUE TITLE
Eboard needs to be updated

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/softe.club#318]
The following eboard member positions are out of date on https://softe.club/team

- [x] President
- [x] Vice President
- [x] Treasurer
- [x] Secretary
- [ ] Logistics Chair
- [ ] Marketing Chair

Each eboard member should make their own PR with the changes to their position. **This is your opportunity to make sure you have your local dev environment for the website working.** It shouldn't take more than 10 minutes to do this.

The images should be replaced with similar headshots. **They must be square, or they will be distorted.** See the current existing headshots for examples.

**Comment by MHKhan18** [comment]
Accidentally closed the issue. Other e-board members still need to update their information.

**Comment by dyc3** [comment]
@MHKhan18 Please crop your image to a square and make a new PR. **Do not merge it without a review.**

![image](https://user-images.githubusercontent.com/1808807/201493735-351a3620-20b0-4193-9243-dede098c8bd7.png)

**Comment by dyc3** [comment]
Closing this as wont fix because it's almost the end of the school year.
